server:
  port: 80

spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/bootdemo
      username: root
      password: wxy31425
   jpa:
     hibernate.ddl-auto: update
     show-sql: true


   freemarker:
       template-loader-path: classpath:/templates/
       spring.freemarker.settings:
       prefer-file-system-access: true
       charset: UTF-8
       check-template-location: true
       suffix: .ftl
       content-type: text/html
       allow-request-override: false
       allow-session-override: false
       expose-request-attributes: false
       expose-session-attributes: false
       expose-spring-macro-helpers: true
       date_format: yyyy-MM-dd
       time_format: HH:mm:ss
       datetime_format: yyyy-MM-dd HH:mm:ss
       template_update_delay: 0

